##########
# ESLint #
##########
# [INFO] ESLint configuration:
# https://eslint.org/docs/latest/use/configure/
#
# [INFO] Specific environments for different JavaScript runtimes, versions, extensions, and frameworks:
# https://eslint.org/docs/latest/use/configure/language-options
#
# [INFO] eslint-plugin-autofix — autofix many ESLint rules:
# https://github.com/aladdin-add/eslint-plugin/tree/master/packages/autofix
# env:

  # [INFO] Support browser JavaScript global variables.
  #
  # If “browser: true”, ESLint, will not throw errors, for example:
  # “'document' is not defined” for “document.querySelectorAll(".KiraClass")” or
  # “'console' is not defined” for “console.log("Kira Goddess!")”
  #
  # I enable it as my JavaScript files for use in the browser:
  # https://eslint.org/docs/latest/use/configure/language-options#specifying-environments
  # browser: true


# [INFO] Rule sets:
# https://eslint.org/docs/latest/use/configure/configuration-files#extending-configuration-files
extends:
# [INFO] Enable all core rules in the currently installed version of ESLint:
# https://eslint.org/docs/latest/use/configure/configuration-files#using-eslintall
- eslint:recommended

# [INFO] The solely set of settings by the author of the compat plugin:
# https://github.com/amilajack/eslint-plugin-compat/tree/main/src/config
- plugin:putout/recommended


# [INFO] Ignore specific patterns:
# https://eslint.org/docs/latest/use/configure/ignore
#
# [NOTE] “node_modules/” and dot-files ignored by default:
# https://eslint.org/docs/latest/use/configure/ignore#the-eslintignore-file
# https://github.com/eslint/eslint/issues/10341
#
# [INFO] Add “!.*” that enable ESLint for dot-files:
# https://stackoverflow.com/a/71829427/5951529
ignorePatterns:
- "!.*"


# [INFO] Setting to enable support for non-default ECMAScript versions and JSX
parserOptions:

  # [INFO] The most recently supported ECMAScript version.
  # ECMAScript 5 syntax by default:
  # https://eslint.org/docs/latest/use/configure/language-options#specifying-parser-options
  ecmaVersion: latest


plugins:
- putout


rules:
  indent: off
