clone_depth: 10

version: "{build}"

platform: x64

# What combinations to test
environment:
  matrix:
    - nodejs_version: "21"

install:
  - ps: Install-Product node $env:nodejs_version
  - npm install

test_script:
  - node --version && npm --version
  - npm test

build: off

matrix:
  fast_finish: true

cache:
  - node_modules -> package.json
